[package]
name = "blake3-smol"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[features]
std = []
no_avx512 = []
no_avx2 = []
no_sse41 = []
no_sse2 = []

[dependencies]
constant_time_eq = "0.3.0"

[dev-dependencies]
rand = "0.8.0"
rand_chacha = "0.3.0"