[package]
name = "blake3-smol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constant_time_eq = "0.3.0"

[dev-dependencies]
rand = "0.8.0"
rand_chacha = "0.3.0"