[workspace]

members = [
    "ffi/vulkan-sys",
    "ffi/sdl2-sys",
    "ffi/renderdoc-sys",
    "narcissus",
    "narcissus-core",
    "narcissus-gpu",
    "narcissus-app",
    "narcissus-maths",
    "narcissus-world",
]

[profile.release]
panic = "abort"
debug = true
opt-level = 3
lto="thin"

[profile.dev]
panic = "abort"
opt-level = 1
