[workspace]

members = [
    "bins/narcissus",
    "libs/ffi/renderdoc-sys",
    "libs/ffi/sdl2-sys",
    "libs/ffi/stb_image-sys",
    "libs/ffi/stb_truetype-sys",
    "libs/ffi/vulkan-sys",
    "libs/narcissus-app",
    "libs/narcissus-core",
    "libs/narcissus-font",
    "libs/narcissus-gpu",
    "libs/narcissus-image",
    "libs/narcissus-maths",
    "libs/narcissus-world",
]

[profile.release]
panic = "abort"
debug = true
opt-level = 3
lto="thin"

[profile.dev]
panic = "abort"
opt-level = 0
