[package]
name = "narcissus-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
narcissus-core = { path = "../narcissus-core" }
sdl2-sys = { path = "../../external/sdl2-sys" }