[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=/usr/bin/mold",
    "-C", "link-arg=-Wl,--compress-debug-sections=zstd",
    "-C", "target-cpu=x86-64-v3",
    "-C", "force-frame-pointers=yes"
]